server:
    servlet:
        context-path: /shop-api
    port: 9876
    compression:
        enabled: true
spring:
    main:
        banner-mode: "off"
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/shop
        username: test
        password: test
        tomcat:
            initialSize: 1
            minIdle: 3
            maxActive: 5
            maxWait: 2000
            validationQuery: "/* Health Check */ SELECT 1"
            validationQueryTimeout: 3
            testWhileIdle: true
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.generate_statistics: false
            hibernate.temp.use_jdbc_metadata_defaults: false
logging:
    config: classpath:log4j.properties